### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by urrgur** [h5bp/server-configs-iis#25]
https://github.com/h5bp/server-configs-iis/blob/master/dotnet%203/web.config#L293

**Comment by arthurvr** [comment]
Yep! Thanks for letting us know!

**Comment by ChrisMcKee** [comment]
There's minor differences between the configs as each version of .net adds little changes. I'm going to reduce all the configs to 1 current one rather than trying to support every variant. Maybe add in the varying .net x required bits in comments. So i'll let the dead link slide for now as its destined for deletion.
